### ISSUE TITLE
Question about ig_pred

### ISSUE THREAD

**Issue by zhizhou57** [Hunter-DDM/knowledge-neurons#11]
hello,
I have a question: why ig_pred is computed but not used in your project. It seems that all the gradients are computed based on golden label. Is there some reason?

**Comment by DeepSeekDDM** [comment]
We aim to analyze the influence on the probability of the true fact, but not the predicted one, so we use IG w.r.t. the golden label.

**Comment by zhizhou57** [comment]
ok,thanks
