### ISSUE TITLE
Question about your code

### ISSUE THREAD

**Issue by sh0416** [Hunter-DDM/knowledge-neurons#3]
https://github.com/Hunter-DDM/knowledge-neurons/blob/922dfd9e05ef55f46af078ba4bd334989a45a618/src/1_analyze_mlm.py#L292

I don't know why the output is gradient.. could you please explain about it?

**Comment by Hunter-DDM** [comment]
The code of the BERT model is not the official HuggingFace version. Please see custom_bert.py Line 547-550. We compute and return the gradient here.

**Comment by sh0416** [comment]
Nice. Thank you
