### ISSUE TITLE
Question about load pretrained model 

### ISSUE THREAD

**Issue by xiatingyu** [Hunter-DDM/knowledge-neurons#6]
Hello,
When I wanted to load pretrained model, I faced this problem:

- INFO - custom_bert -   Weights from pretrained model not used in BertForMaskedLM: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']

**Comment by xiatingyu** [comment]
Sorry it is my fault, The code is ok.

**Comment by Destiny-Suk** [comment]
Hello, I also encountered this problem, what is the cause? Or, how did you solve it?
Moreover, can you tell me the dependencies to run this code?
Thank you very much!

**Comment by xiatingyu** [comment]
> Hello, I also encountered this problem, what is the cause? Or, how did you solve it? Moreover, can you tell me the dependencies to run this code? Thank you very much!

I'm so sorry. It's been so long, and I lose the code.
