### ISSUE TITLE
Computational cost for calculating attribution scores

### ISSUE THREAD

**Issue by SCccc21** [Hunter-DDM/knowledge-neurons#7]
Hi, I'm currently running the first step `bash 1_run_mlm.sh` to get attribution scores, and I found it took several hours. Is it normal? In your paper you reported theh running time for identifying knowledge neurons is only 13.3 seconds. So this is the time cost for the second step `bash 2_run_kn.sh`, not the first step right?

**Comment by SCccc21** [comment]
I am using A100 GPUs.

**Comment by Hunter-DDM** [comment]
13.3 seconds is the time for a triplet (with 9 templates). If you have 1K triplets, it may take about 13.3K seconds (≈3.7 hours). So the time cost is normal.

**Comment by SCccc21** [comment]
Thanks for the clarification!
