### ISSUE TITLE
knowledge neuron in transformers that have both encoder and decoder

### ISSUE THREAD

**Issue by SCccc21** [Hunter-DDM/knowledge-neurons#8]
Hi, 

Firstly I want to thank you for the paper, which is very inspiring and interesting. I am wondering if you have ever tried to identity knowledge neurons in other transformers (in you paper you evaluated BERT models, which is encoder-only). Just curious about what would the knowledge neuron distributed in a model that has both encoder and decoder? Will decoder layers have more knowledge neurons than encoder layers? Or if there any related reference? 

Thanks!

**Comment by Hunter-DDM** [comment]
Hello, thank you for your interest in our work! 

Currently, we haven't conducted further experiments on other architectures. However, based on my understanding, the functioning of knowledge neurons in this paper primarily targets the decoder. Although BERT is an encoder architecture, it also plays a role in decoding the [mask] token near the output layer, and the paper also found that the neurons near the output layer have a closer connection to knowledge. Based on the idea of knowledge neurons, I have also attempted to mount an additional FFN knowledge storage module to the T5 decoder and it works well (https://arxiv.org/pdf/2208.00399.pdf). I hope this information is helpful to you.

**Comment by SCccc21** [comment]
Thanks for the explanation! By 'functioning of knowledge neurons in this paper primarily targets the decoder', do you mean that knowledge storage is more related to decoders than encoders, either for semantic patterns or shallow patterns? Or, it could be in a way that semantic patterns (like the facts evaluated in this paper) are more tied to decoder, while shallow patterns that are meaningless are more tied to encoder?

**Comment by Hunter-DDM** [comment]
"Knowledge" I mentioned is factual knowledge. In my opinion, knowledge stored in the decoder can be easier to be used in generation. Encoders/shallow layers may play a role that decides what knowledge to use.

**Comment by Hunter-DDM** [comment]
If you have more to discuss, welcome to mail me and we can make a WeChat phone call. Messages in GitHub may be missed by me sometimes.
